In [1]:
import torch
import torchvision.models as models
import torch.nn as nn
from subspace_wrapper import to_subspace_class
import numpy as np

In [2]:
SubLinear = to_subspace_class(nn.Linear, num_vertices=3, verbose=True)

l = SubLinear(5,5)

l(torch.rand(5))

# SubResNet = to_subspace_class(models.ResNet, verbose=True)
# sub_resnet18 = SubResNet(models.resnet.BasicBlock, [2, 2, 2, 2])

# sub_resnet18.to('cuda:3')

# out = sub_resnet18(torch.rand(100, 3, 224, 224).to('cuda:3'))

Setting parameters from subspace parametrization...
Done setting parameters!


tensor([ 0.1496,  0.1241, -0.2891, -0.5524,  0.1146], grad_fn=<AddBackward0>)

In [3]:
ln = nn.Linear(5,5)

In [5]:
l.state_dict().keys()

odict_keys(['weight', 'bias', 'num_base_parameters', 'num_vertices', 'alpha', 'parametrization_points.0', 'parametrization_points.1', 'parametrization_points.2', 'parametrization_points.3', 'parametrization_points.4', 'parametrization_points.5'])

In [7]:
ln.state_dict().keys()

odict_keys(['weight', 'bias'])

In [8]:
incompatible_keys = l.load_state_dict(ln.state_dict())
incompatible_keys

Found {'parametrization_points.3', 'parametrization_points.5', 'num_base_parameters', 'parametrization_points.0', 'parametrization_points.4', 'num_vertices', 'alpha', 'parametrization_points.2', 'parametrization_points.1'} missing keys, and assuming that they are copies for the parametrization so will fill up accordingly.


KeyError: 'weight'

In [24]:
l.orig_parameter_names

['weight', 'bias']

In [23]:
l.state_dict()['parametrization_points.4']

tensor([ 0.4136, -0.1971, -0.1073, -0.0292,  0.3968])

In [17]:
ln.state_dict()[l.param_point_keys_to_orig_state_keys['parametrization_points.4']]

tensor([-0.4161, -0.0038, -0.2463,  0.0211,  0.3537])

In [4]:
device = 'cuda:3'
SubspaceTransformer = to_subspace_class(nn.Transformer, num_vertices=1, verbose=True)
transformer_model = SubspaceTransformer(nhead=16, num_encoder_layers=12).to(device)
src = torch.rand((10, 32, 512)).to(device)
tgt = torch.rand((20, 32, 512)).to(device)
out = transformer_model(src, tgt)

Setting parameters from subspace parametrization...
Done setting parameters!


In [3]:
out.shape

torch.Size([20, 32, 512])

In [6]:
[1,2,3][np.floor(5/3).astype(int)]

2